---
- hosts: "{{ instance_name }}"
  pre_tasks:
    - name: Add mariadb Repository Key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 0xF1656F24C74CD1D8
        state: present
      when: "'mariadb-server' in mysql_packages"

    - name: Add mariadb Repository
      apt_repository:
        repo: "deb http://mirror.terrahost.no/mariadb/repo/10.4/ubuntu bionic main"
        state: present
        filename: MariaDB
      when: "'mariadb-server' in mysql_packages"

  roles:
    - hoplacloud.apache_php
    - geerlingguy.mysql
