---
- hosts: "{{ instance_name }}"
  vars:
    ansible_port: "{{ hostvars[instance_name]['openstack']['metadata'].ssh_pub_port }}"
    ansible_host: "{{ hostvars[instance_name]['openstack']['metadata'].ssh_pub_ip }}"
  roles:
    - hoplacloud.inf_deluser
    - hoplacloud.linuxbase
