---
- hosts: "{{ instance_name }}"
  vars:
    ansible_user: "{{ default_username }}"
  roles:
    - hoplacloud.inf_adduser

- hosts: "{{ instance_name }}"
  roles:
    - hoplacloud.inf_deluser
    - hoplacloud.linuxbase
