---
- hosts: "{{ instance_name }}"
  vars:
    ansible_connection: network_cli
    ansible_network_os: router_os
    ansible_user: admin

  roles:
    - hoplacloud.ansible-role-mikrotik-create-profile
