---
- hosts: localhost
  gather_facts: no
  tasks:
     - os_server_info:
         filters:
           name: "{{ awx_inventory_name }}chr1"
       register: chr_server
     - ansible.builtin.debug:
          msg: "{{ hostvars['localhost'] }}"
     - set_fact:
          mikrotik_ipv4: "{{ chr_server.openstack_servers | json_query('[].private_v4') | join('\n') }}"
          mikrotik_id: "{{ chr_server.openstack_servers | json_query('[].id') | join('\n') }}"
     - ansible.builtin.debug:
          msg: mikrotik_ipv4 {{ mikrotik_ipv4 }}
     - os_port_info:
         filters:
           device_id: "{{ mikrotik_id }}"
       register: chr_port
     - set_fact:
          query_gw_v4: "[?ip_address=='{{ mikrotik_ipv4 }}'].subnet_id"
          subnet_id_v4: "{{ chr_port.openstack_ports | json_query('[].fixed_ips[]') }}"
     - set_fact:
          subnet_id_v4: "{{ subnet_id_v4 | json_query(query_gw_v4) | join('\n') }}"
     - os_subnets_info:
         filters:
           id: "{{ subnet_id_v4 }}"
       register: chr_subnet
     - set_fact:
          gw_ipv4: "{{ chr_subnet.openstack_subnets | json_query('[].gateway_ip') | join('\n') }}"
          cidr_ipv4: "{{ chr_subnet.openstack_subnets | json_query('[].cidr') | join('\n') }}"
          netmask_ipv4: "{{ cidr_ipv4 | ansible.netcommon.ipaddr('netmask') }}"
          network_ipv4: "{{ cidr_ipv4 | ansible.netcommon.ipaddr('address') }}"
- hosts: "{{ instance_name }}"
  vars:
    ansible_connection: network_cli
    ansible_network_os: routeros
    ansible_user: admin

 
  roles:
    - hoplacloud.mikrotik_create_profile
