galaxy_info:
  role_name: linuxbase
  author: hoplacloud
  description: Hopla.cloud role for ansible to set a minimal configration for linux systems
  company: hopla.cloud
  license: GPLv3

  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - linux
    - hoplacloud

dependencies:
    - hoplacloud.linux_motd
    - hoplacloud.fail2ban
    - hoplacloud.postfix
