---
# tasks file for hoplacloud.postfix

- name: Install latest version of postfix
  apt:
    name: postfix
    state: latest

- name: Install python-dnspython
  apt:
    name: python-dnspython
    state: latest

- name: Get public IP
  ipify_facts:

- name: This is the target public IP and the reverse DNS
  debug:
    msg: Reverse DNS for {{ ipify_public_ip }} is {{ lookup('dig', ipify_public_ip, 'qtype=PTR')[:-1] }}

- name: Setup smtpd_banner in postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^smtpd_banner'
    line: 'smtpd_banner = $myhostname ESMTP'


- name: Setup myhostname in postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^myhostname'
    line: "myhostname = {{ lookup('dig', ipify_public_ip | join, 'qtype=PTR')[:-1] }}"

- name: Setup inet_protocols to IPV4
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_protocols'
    line: "inet_protocols = ipv4"

- name: Restart postfix
  service: name=postfix state=restarted
