galaxy_info:
  role_name: linux_motd
  author: hoplacloud
  description: Hopla.cloud role for ansible to set motd
  company: hopla.cloud
  license: GPLv3

  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: EL
      versions:
        - 7
        
  galaxy_tags:
    - linux
    - motd
    - hoplacloud

dependencies: []
