---
# tasks file for hoplacloud.letsencrypt


- name: Set server_type from inventory metadata
  set_fact:
    server_type: "apache"
  when: "'meta-is_apache_true' in group_names"

- name: Set server_type from inventory metadata
  set_fact:
    server_type: "nginx"
  when: "'meta-is_nginx_true' in group_names"

- name: Install Certbot (letsencrypt) PPA Repository
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install Certbot for {{ server_type }} web server
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - python-certbot-{{ server_type }}
