galaxy_info:
  role_name: postfix
  author: Joffrey Skandera
  description: Hopla.cloud role for ansible to install and configure postfix
  company: hopla.cloud

  license: GPLv3

  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
  galaxy_tags:
    - postfix
    - email

dependencies:
    - hoplacloud.linux_update
    - hoplacloud.linux_motd
