---
# tasks file for iilyo.wasi-apache-sn

- name: Install Ondrej Apache2 PPA Repository
  apt_repository:
    repo: 'ppa:ondrej/apache2'

- name: Install Ondrej PHP PPA Repository
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install Certbot (letsencrypt) PPA Repository
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install Apache2, PHP-FPM and LetsEncrypt Packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - apache2
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-mysql
    - php{{ php_version }}-xml
    - php{{ php_version }}-zip
    - php{{ php_version }}-gd
    - php{{ php_version }}-curl
    - php{{ php_version }}-bz2
    - php{{ php_version }}-fpm
    - php{{ php_version }}-intl
    - php{{ php_version }}-json
    - php-apcu
    - python-certbot-apache
    - mariadb-client
    - fail2ban

- name: Enabling Apache2 modules
  apache2_module: name={{ item }} state=present
  with_items:
    - proxy_fcgi
    - setenvif
    - headers
    - rewrite
    - deflate
    - http2

- name: Disabling Apache2 indexes modules
  apache2_module: name={{ item }} state=absent force=true
  with_items:
    - autoindex

- name: Configure Apache2 basic security (ServerTokens)
  lineinfile:
    path: /etc/apache2/conf-available/security.conf
    regexp: '^ServerTokens'
    line: 'ServerTokens prod'
  notify:
    - restart apache

- name: Configure Apache2 basic security (ServerSignature)
  lineinfile:
    path: /etc/apache2/conf-available/security.conf
    regexp: '^ServerSignature'
    line: 'ServerSignature Off'
  notify:
    - restart apache

- name: Remove default Apache site directory
  file:
    state: absent
    path: /var/www/html

- name: Create new Apache site directory
  file:
    path: /var/www/default_site
    state: directory
    mode: 0755
        
- name: Create new Apache site directory index.html
  file:
    path: /var/www/default_site/index.html
    state: touch
    mode: 0755
        
- name: Patching default non-ssl vhost 
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '\t*DocumentRoot'
    line: 'DocumentRoot /var/www/default_site'
  notify:
    - restart apache

- name: Patching default ssl vhost
  lineinfile:
    path: /etc/apache2/sites-available/default-ssl.conf
    regexp: '\t*DocumentRoot'
    line: 'DocumentRoot /var/www/default_site'
  notify:
    - restart apache

- name: Patching default non-ssl vhost (admin email)
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: '\t*ServerAdmin'
    line: 'ServerAdmin {{ customeradmin }}'
  notify:
    - restart apache

- name: Patching default ssl vhost (admin email)
  lineinfile:
    path: /etc/apache2/sites-available/default-ssl.conf
    regexp: '\t*ServerAdmin'
    line: 'ServerAdmin {{ customeradmin }}'
  notify:
    - restart apache

- name: Sending the php.ini configuration file (FPM)
  template:
    src: php.ini.j2
    dest: /etc/php/{{ php_version }}/fpm/php.ini
  notify:
    - restart php-fpm

- name: Sending the php.ini configuration file (CLI)
  template:
    src: php.ini.j2
    dest: /etc/php/{{ php_version }}/cli/php.ini
  notify:
    - restart php-fpm

- name: Install ProFTPd Packages
  apt: name=proftpd state=latest update_cache=yes

- name: Copy Configuration file
  copy:
    src: files/proftpd.conf
    dest: /etc/proftpd/proftpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart proftpd

- name: Creating /usr/local/bin/ftponly shell
  file:
    path: /usr/local/bin/ftponly
    state: touch

- name: Adding /usr/local/bin/ftponly to valid system shells
  lineinfile:
    path: /etc/shells
    line: '/usr/local/bin/ftponly'

- name: Creating websites directory /var/www/custs
  file:
    path: /var/www/custs
    state: directory

- name: Creating home symlink to /var/www/custs
  file:
    src: /var/www
    dest: /home/{{ customerid }}/my_websites
    state: link

- name: Temporary copy the SSH private key to checkout GitLab repos
  copy:
    src: /root/.ssh/id_rsa.siilyo
    dest: /etc/iiprov/.ssh/id_rsa.siilyo
    owner: iiprov
    group: iiprov
    mode: u=rw,g=,o=

- name: Checkout the vhost_deploy script for Single Node on GitLab
  git:
    repo: 'git@gitlab.com:iilyoteam/vhost_deploy_apache.git'
    dest: /usr/src/vhost_deploy_apache
    accept_hostkey: yes
    key_file: /etc/iiprov/.ssh/id_rsa.siilyo
    force: yes

- name: Set the X right to vhost_deploy.sh script
  file:
    path: /usr/src/vhost_deploy_apache/vhost_deploy.sh
    mode: 0755

- name: Creating symlink for vhost_deploy.sh script
  file:
    src: /usr/src/vhost_deploy_apache/vhost_deploy.sh
    dest: /usr/local/sbin/vhost_deploy
    state: link

- name: Delete the temporary SSH private key
  file:
   state: absent
   path: /etc/iiprov/.ssh/id_rsa.siilyo

- name: Configure the customer ID in vhost_deploy.sh script
  lineinfile:
    path: /usr/src/vhost_deploy_apache/vhost_deploy.sh
    regexp: '^adminUser'
    line: 'adminUser="{{ customerid }}"'

- name: Configure the customer Email in vhost_deploy.sh script
  lineinfile:
    path: /usr/src/vhost_deploy_apache/vhost_deploy.sh
    regexp: '^adminEmail'
    line: 'adminEmail="{{ customeradmin }}"'

- name: Configure the PHP version in vhost_deploy.sh script (phpfpmDaemonName)
  lineinfile:
    path: /usr/src/vhost_deploy_apache/vhost_deploy.sh
    regexp: '^phpfpmDaemonName'
    line: 'phpfpmDaemonName="php{{ php_version }}-fpm"'

- name: Configure the PHP version in vhost_deploy.sh script (phpfpmPoolPrefix)
  lineinfile:
    path: /usr/src/vhost_deploy_apache/vhost_deploy.sh
    regexp: '^phpfpmPoolPrefix'
    line: 'phpfpmPoolPrefix="/etc/php/{{ php_version }}/fpm/pool.d"'
