---
# defaults file for iilyo.wasi-apache-sn

#
# PHP variables
#

# Possible : 5.6 7.0 7.1 7.2
php_version: "7.2"

post_max_size: "64M"
upload_max_filesize: "64M"
short_open_tag: "On"

# Memcached
session_save_handler: "files"
session_save_path: "/var/lib/php/sessions"
